### ISSUE TITLE
Stopped working for me when Slicer-plugin ("Full-Featured Slicer") is used

### ISSUE THREAD

**Issue by bagong** [stefancandrea/OctoPrint-Thingiverse#1]
Hi, and thanks, for this plugin! I enjoyed it (using also the themeing option) until I felt the need to install the "Full featured Slicer" plugin. Then, unfortunately, the Thingiverse plugin stopped displaying anything in the respective tab/frame.

This is on a Raspberry Pi 3b (not plus) running Raspbian Buster. While this is a manual Octoprint install (13.12), everything else seems to work as expected (as did the Thingiverse-Plugin until I added the Slicer plugin) - so I am quite sure it is a Thingiverse or FFSlicer problem. I tried to reinstall the Thingiverse plugin, to no avail ;)

Maybe this screenshot of the browser-console can shed some light on the issue?

<img width="1419" alt="Screenshot 2019-10-31 at 00 41 22" src="https://user-images.githubusercontent.com/1502057/67907142-43e0d980-fb77-11e9-9c7d-fee908c2b961.png">

**Comment by stefancandrea** [comment]
**UPDATE:** I've written to Thingiverse support, maybe they will help me and set a CSP (Content Security Policy) for the thingiverse.com website to be displayed inside an iframe, outside of already allowed domains. I hope they will help.

Thanks for using the plugin, I'm very happy that someone is using my first plugin, and thanks for the feedback :)

I don't think it's the Slicer Plugin causing the problem. I have the same problem, the screen is white when I search something.
I think Thingiverse Website has a "feature" that blocks the content from the website to be displayed inside an iframe.

I'll try to debug the problem :)

Thanks again :)

**Comment by stefancandrea** [comment]
Hi all,
Thanks for the support, and sorry I could not solve the problem.

The latest release 1.1.0 with Python 3 compatible will explain the situation.

Explications:
The plugin will no longer work. This is left here as a reminder for someone who will build a new Octoprint Thingiverse Plugin directly from the Thingiverse API.
This is why the plugin doesn't work anymore, and the Thingiverse team does not allow me to run this plugin inside an iframe, because then have an API.

So maybe if someone has time and is willing to build such a thing, that will be great.

This repository is open for everyone, for then mentioned task.

V1.1.0: Python 3 compatible.
