### ISSUE TITLE
Can't use plugin in Firefox - it blocked by security policy

### ISSUE THREAD

**Issue by mishich666** [stefancandrea/OctoPrint-Thingiverse#3]
but I disabled all content security policies
![image](https://user-images.githubusercontent.com/54218627/68072224-ba125580-fd9c-11e9-92db-8f823c4699e5.png)

**Comment by stefancandrea** [comment]
Hello,

I'm aware of this problem, I've contacted Thingiverse.com and maybe they will help me by removing the CSP restriction.

Thanks.

**Comment by desertwalker66** [comment]
I am having issues with chrome, firefox and safari. The plugin just does not work at all

**Comment by pquodling** [comment]
Just a me too, so that I get notified when fixed.

**Comment by stefancandrea** [comment]
Hello,

Thanks for using the plugin (sort of) and thanks for the feedback.
The error is known, and I'm trying to solve it.

This is what cause the error:
Refused to display 'https://www.thingiverse.com/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors *.makerbot.com *.thingiverse.com *.mbot.me *.onshape.com".

The Thingiverse website has a Security Policy that does not allow iframes to display outside of their domain (allowed domains, they are specified in the directive)

I've mailed Makerbot, maybe they will help me and remove this policy.

Thanks.

**Comment by Releece** [comment]
Was this CSP so recently added to thingiverse.com then? Because you released this plug-in 19 days ago (I assume it worked at that time) and already 14 days ago this issue was submitted. I hope they'd be willing to modify their CSP to make use like this possible again. It would be a great plug-in! 

Maybe you could write the plug-in to access Thingiverse through a proxy which removes the CSP header before it reaches the users browser?

**Work-around for chrome users**: there is an [extension](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden) which enables/disables CSP handling on the current page by clicking on it's icon. 

I'm a Firefox user unfortunately. You can only completely turn CSP off for the whole browser by going to the `about:config` menu and setting `security.csp.enable` to false. However this is unsafe if you are using any other website concurrently and it is too much of a hassle to do this everytime you want to use this plugin.

**Comment by stefancandrea** [comment]
Hello,

Sorry I did not make any changes to the code, but I had a little holiday. I'll try to make this work. I've received a possible fix and I'll try to embed it into the plugin.

Thanks.

**Comment by oudinit** [comment]
Hello,
security problem here too.
Sorry but the plugin just does not work.

**Comment by stefancandrea** [comment]
Hi all,
Thanks for the support, and sorry I could not solve the problem.

The latest release 1.1.0 with Python 3 compatible will explain the situation.

Explications:
The plugin will no longer work. This is left here as a reminder for someone who will build a new Octoprint Thingiverse Plugin directly from the Thingiverse API.
This is why the plugin doesn't work anymore, and the Thingiverse team does not allow me to run this plugin inside an iframe, because then have an API.

So maybe if someone has time and is willing to build such a thing, that will be great.

This repository is open for everyone, for then mentioned task.

V1.1.0: Python 3 compatible.
