### ISSUE TITLE
Not loading the site

### ISSUE THREAD

**Issue by NewMC** [stefancandrea/OctoPrint-Thingiverse#4]
Not working in Chrome for latest Octopi image with Octoprint 1.3.12.  I installed this plugin using the plugin manager, reloaded web interface, installed Themeify (via plugin mgr), reloaded, and added the css rules, reloaded one last time at this point if it prompted a reload.  The Thingiverse tab and the iframe are visible, but the iframe is blank.  I've tried in Chrome on multiple computers with the same results.  When I try with MS Edge there is a message that says the publisher does not allow the content to be displayed in a frame.  I've also rebooted the Pi3B that I'm running Octoprint from, no change.

Thank you!

**Comment by desertwalker66** [comment]
Hello, I too am having the same issue. I have tried with safari, firefox and chrome, using all the same techniques as you have.

**Comment by stefancandrea** [comment]
Hello,

Thanks for using the plugin (sort of) and thanks for the feedback.
The error is known, and I'm trying to solve it.

This is what cause the error:
Refused to display 'https://www.thingiverse.com/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors *.makerbot.com *.thingiverse.com *.mbot.me *.onshape.com".

The Thingiverse website has a Security Policy that does not allow iframes to display outside of their domain (allowed domains, they are specified in the directive)

I've mailed Makerbot, maybe they will help me and remove this policy.

Thanks.

**Comment by Twoods1984** [comment]
Just some thoughts as ive dealt with this issue before on other projects ive created. 1st the simplest way(at first) So this way is just by having each user required to have the install Requestly browser extension. It allows you to modify the HTTPS request. So you can setup a rule in it to remove the X-Frame-Option (I assume they are using this method as its the only one thats not easily by-passed)
So that option requires the end user to install Requestly and setup a rule. (Don't worry firefox users you can use this plugin: https://addons.mozilla.org/en-us/firefox/addon/modify-response-headers/)

2nd way and would require more work on the development side but the end-user would have a nice interaction with the plugin. That's using something like https://www.charlesproxy.com/ this will allow you to set up a proxy that the iframe is tunneled through. It allows you to modify it so that the X-FRAME OPTION gets removed. It will basically be tunnelling all the traffic through this proxy and then back to your plugin.

If you need any other help let me know as there is other ways to do it that people frown upon. Thanks for the plugin!

**Comment by Twoods1984** [comment]
Below is a screenshot with the 2 rules you need to setup in the extension. Also is a screenshot showing it now working. Good Luck
**Note: To NOT allow every site to do this then in the URL > Contains field put thingiverse.com**
![ThingiVerse1](https://user-images.githubusercontent.com/37712032/68996124-75d28b00-085b-11ea-95e0-ab22214f5f61.JPG)
![ThingiVerse2](https://user-images.githubusercontent.com/37712032/68996129-7c610280-085b-11ea-82f7-cddb3ce69049.JPG)
![ThingiVerse3](https://user-images.githubusercontent.com/37712032/68996133-8256e380-085b-11ea-83c3-de462d9c085e.JPG)

**Comment by RayEbb** [comment]
> Below is a screenshot with the 2 rules you need to setup in the extension. Also is a screenshot showing it now working. Good Luck
> **Note: To NOT allow every site to do this then in the URL > Contains field put thingiverse.com**


Thank you very much, Twoods1984!!

**Comment by Twoods1984** [comment]
No Problem, as this bug will affect every user the temp or perm fix(however you look at it) should be provided in the main git or on the Octopi page for this plugin. As I'm sure there are a lot of people that do not look in the bug section and just uninstall it.

Edit: Wanted to add for the dev a simple fix would be to eliminate the iframe and scrape the source. This would allow more ability to customize the UI. I'm sure you have already thought of this but thought I would drop it in just-in-case.

**Comment by stefancandrea** [comment]
Hello,

Thanks all for the reply, I will try to embed Twoods1984 response, inside the plugin, i'll try to eliminate the X-Frame-Option.

I hope is not a hack so Thingiverse website will block the plugin, but let's hope for the best :)

Thanks Twoods1984 .

**Comment by MikeUSNRet** [comment]
Getting anywhere with this?  Just re-installed the plugin about 15 mins ago and still coming up with a blank screen...

**Comment by squrrell** [comment]
Same here. I've set up both rules as shown, restarted the OctoPi server OS. cleared my browser cache and restarted it. I didn't uninstall/re-install the plugin, but I did disable then re-enable it and restart the OctoPi server process. I'm still getting "www.thingiverse.com refused to connect."

**Comment by stefancandrea** [comment]
Hello, 
Yes I know.. the Thingiverse changed their website... I'm in disscutions with them to allow me to freely use the website from an IFrame without other reverse proxy and HTTP Request modifiers but... they don't look very cool with it... so...

For the moment the plugin is not working. I'm... Sorry!

**Comment by stefancandrea** [comment]
P.S. 

They saw the workaround, that is here on past messages.. and they didn't liked it.
1 or 2 weeks with that modification, you could make the plugin work.. but after that they changed the website.

**Comment by Bitburg-chef** [comment]
Hello, 
This is an unfortunate and annoying thing...thingiverse! 
One would think that they would like their platform being integrated on various sites and shared as well as used across a widely known interface platforms as it would increase their user base, ad placement and whatnot; but at the same time they are not able to maintain their own app to work properly, had several issues with their website for years and server outages on a frequent basis... 

I liked your work-around and hope your negotiations with them go well. let us know if you find out anything :-)

**Comment by stefancandrea** [comment]
Hi all,
Thanks for the support, and sorry I could not solve the problem.

The latest release 1.1.0 with Python 3 compatible will explain the situation.

Explications:
The plugin will no longer work. This is left here as a reminder for someone who will build a new Octoprint Thingiverse Plugin directly from the Thingiverse API.
This is why the plugin doesn't work anymore, and the Thingiverse team does not allow me to run this plugin inside an iframe, because then have an API.

So maybe if someone has time and is willing to build such a thing, that will be great.

This repository is open for everyone, for then mentioned task.

V1.1.0: Python 3 compatible.
