### ISSUE TITLE
Just some thoughts as ive dealt with this issue before on other projects ive created. 1st the simplest way(at first) So this way is just by having each user required to have the install Requestly browser extension. It allows you to modify the HTTPS request. So you can setup a rule in it to remove the X-Frame-Option (I assume they are using this method as its the only one thats not easily by-passed)

### ISSUE THREAD

**Issue by desertwalker66** [stefancandrea/OctoPrint-Thingiverse#5]
Just some thoughts as ive dealt with this issue before on other projects ive created. 1st the simplest way(at first) So this way is just by having each user required to have the install Requestly browser extension. It allows you to modify the HTTPS request. So you can setup a rule in it to remove the X-Frame-Option (I assume they are using this method as its the only one thats not easily by-passed)
So that option requires the end user to install Requestly and setup a rule. (Don't worry firefox users you can use this plugin: https://addons.mozilla.org/en-us/firefox/addon/modify-response-headers/)

2nd way and would require more work on the development side but the end-user would have a nice interaction with the plugin. That's using something like https://www.charlesproxy.com/ this will allow you to set up a proxy that the iframe is tunneled through. It allows you to modify it so that the X-FRAME OPTION gets removed. It will basically be tunnelling all the traffic through this proxy and then back to your plugin.

If you need any other help let me know as there is other ways to do it that people frown upon. Thanks for the plugin!

_Originally posted by @Twoods1984 in https://github.com/stefancandrea/OctoPrint-Thingiverse/issues/4#issuecomment-554650623_

**Comment by desertwalker66** [comment]
Just letting you know that the firefox addon link you provided does not work, it is not available.
Many Thanks though.

**Comment by Twoods1984** [comment]
Was this ever fixed? I noticed an update saying x-frame fix and since I wrote the original solution above I haven't updated it. So curious if it's been fixed, if not an people are interested I can write a fix to make it work but hopefully it already is. Thanks for the plugin @stefancandrea

**Comment by Twoods1984** [comment]
> Just letting you know that the firefox addon link you provided does not work, it is not available.
> Many Thanks though.

You prob. dont need this now but here is a link to another plugin that will allow you to modify your headers for Firefox. Adding it for anyone that may run across this in the future and need it.
[ModHeader Link-Download](https://addons.mozilla.org/en-US/firefox/addon/modheader-firefox/)
Click the link above or copy and paste the link from below
https://addons.mozilla.org/en-US/firefox/addon/modheader-firefox/

For future-proofing, if this addon is no longer available when you find this comment go to the firefox addon search page and just search for an addon to "modify request headers" Below is a link to FireFox Search Page
[FireFox Addon Search](https://addons.mozilla.org/en-US/firefox/)

and a raw link
https://addons.mozilla.org/en-US/firefox/

Chrome Users, the same thing applies for you except using the chrome extension search page

**Comment by stefancandrea** [comment]
Hy @Twoods1984,

I've tried to fix this... but I could not... I've tried to understand the base principle of that proxy modifier, so that it will not be a legal issue...

I think those guys from thingiverse, set that X_frame for a reason... and I don't know if this modifier header will damage them (legaly, internal security).
I'm still waiting for their email... but no reply yet.

If you want to make the modification, you are free to do so... I will review the modifications and test them, and merge them into master.

Thanks.

**Comment by stefancandrea** [comment]
Hi all,
Thanks for the support, and sorry I could not solve the problem.

The latest release 1.1.0 with Python 3 compatible will explain the situation.

Explications:
The plugin will no longer work. This is left here as a reminder for someone who will build a new Octoprint Thingiverse Plugin directly from the Thingiverse API.
This is why the plugin doesn't work anymore, and the Thingiverse team does not allow me to run this plugin inside an iframe, because then have an API.

So maybe if someone has time and is willing to build such a thing, that will be great.

This repository is open for everyone, for then mentioned task.

V1.1.0: Python 3 compatible.
