### ISSUE TITLE
Unable to log in to Thingiverse within the plugin 

### ISSUE THREAD

**Issue by usnmustanger** [stefancandrea/OctoPrint-Thingiverse#6]
Plugin version:  0.1.0
Browser: Chrome 79.0.3945.88 (Official Build) (64-bit) on Windows 10
Problem: Unable to log in to Thingiverse within the plugin
How to reproduce problem: 
1. Open Thingiverse tab in Octoprint
2. Click "Sign in" at the top right of the Thingiverse plugin frame
3. Enter username & password
4. Click log in
Expected result: User gets logged in to Thingiverse and is able to access saved collections
Actual Result: Login page refreshes, without logging user in, with credentials populated in the username/password fields

This also happens on Firefox as well.

**Comment by Taomyn** [comment]
Having the same issue here, though I'm using Brave rather than Chrome. If I open a new tab on the same browser and access the site my credentials work and I can browse correctly.

**Comment by usnmustanger** [comment]
> Having the same issue here, though I'm using Brave rather than Chrome. If I open a new tab on the same browser and access the site my credentials work and I can browse correctly.

That's strange, this doesn't work for me... I've tried in latest stable builds of Chrome, Brave, and Firefox. Even tried it in a Private window to see if any of my extensions or cache was causing the issue. No dice. No matter what I try, I can't log in to Thingiverse within the Thingiverse plugin tab on Octoprint.

Edit: Jut reread your post--are you saying you can log in to Thingiverse within Octoprint once you log in to the site in another browser tab? Or just that you can log in to Thingiverse normally in a browser tab but still can't log in within the plugin (as in my original report)?

**Comment by samd12** [comment]
Same issue here.

**Comment by stefancandrea** [comment]
Hello,

Yes, I know the plugin is broken, it's a "legal" thingiverse problem.
I'm trying to discuss with them to let me use the website inside OctoPrint.

No luck yet. Sorry.

**Comment by usnmustanger** [comment]
@stefancandrea , thanks for the update! Guess the ball's in their court. With the popularity of Octoprint, hopefully they help you out!

**Comment by inknoidian** [comment]
any updates?  i would love to use this with octoprint

**Comment by stefancandrea** [comment]
Hi all,
Thanks for the support, and sorry I could not solve the problem.

The latest release 1.1.0 with Python 3 compatible will explain the situation.

Explications:
The plugin will no longer work. This is left here as a reminder for someone who will build a new Octoprint Thingiverse Plugin directly from the Thingiverse API.
This is why the plugin doesn't work anymore, and the Thingiverse team does not allow me to run this plugin inside an iframe, because then have an API.

So maybe if someone has time and is willing to build such a thing, that will be great.

This repository is open for everyone, for then mentioned task.

V1.1.0: Python 3 compatible.
